#!/bin/sh

echo "Checking for an older version of SlykEpg7day in the system..."

if [ -d /usr/lib/enigma2/python/Plugins/Extensions/SlykEpg7day ]; then
	rm -rf /usr/lib/enigma2/python/Plugins/Extensions/SlykEpg7day > /dev/null 2>&1
	echo "An older version of SlykEpg7day was found and removed"
	echo "Proceeding to installation..."
else
	echo "SlykEpg7day was not found in the system"
	echo "Proceeding to installation..."
fi

exit 0
